base_url = "http://127.0.0.1:5000/blog"
title = "anurag3301/blog"
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
    {name = "tags"}
]
[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
accent_color = "green"
background_color = "pink"

logo_text = "anurag3301"
logo_home_link = "http://anurag3301.com"
author = "anurag3301"
menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "tags", url = "$BASE_URL/tags"},
    {name = "archive", url = "$BASE_URL/archive"},
    {name = "GitHub", url = "https://github.com/anurag3301", newtab = true},
    {name = "LinkedIn", url = "https://www.linkedin.com/in/anurag3301/", newtab = true},
    {name = "Class Gap", url = "https://www.classgap.com/me/anurag-kumar-singh", newtab = true},
]
enable_post_view_navigation = true
post_view_navigation_prompt = "Thanks for reading! Read other posts?"
use_full_hack_font = true
favicon = "img/favicon.png"
favicon_mimetype = "image/png"
page_titles = "main_only"
